apiVersion: v1
kind: Service
metadata:
  name: {{ include "fwportal.fullname" . }}
  labels:
    {{- include "fwportal.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: fwportal
      protocol: TCP
      name: fwportal
  selector:
    {{- include "fwportal.selectorLabels" . | nindent 4 }}
